# Generated by Django 5.0.6 on 2026-03-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=200, unique=True, verbose_name='ID канала или @username')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Обязательная подписка')),
            ],
            options={
                'verbose_name': 'Канал для подписки',
                'verbose_name_plural': 'Каналы для подписки',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
